name: Deployment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Send Deploy Webhook
      run: |
          curl -X POST \
          -H "Accept: application/json" \
          -H "Content-Type: application/json" \
          -d "{\"token\": \"${{ secrets.TOKEN }}\"}" \
          "http://${{ vars.DOMAIN }}:${{ vars.PORT }}/hooks/${{ vars.KEY }}"
